.TH GPICVIEW "1" "July 2019" "gpicview 0.2.5" "User Commands"
.SH NAME
gpicview \- lightweight image viewer
.SH DESCRIPTION
gpicview has several nice features, between others:
 * Extremely lightweight and fast with low memory usage
 * Very suitable for default image viewer of desktop system
 * Simple and intuitive interface
 * Minimal lib dependency: Only pure GTK+ is used
 * Desktop independent: Doesn't require any specific desktop environment
.SS "Usage:"
gpicview [FILE] \- simple image viewer
.SS "Help Options:"
.TP
\fB\-h\fR, \fB\-\-help\fR
Show help options
.TP
\fB\-\-help\-all\fR
Show all help options
.TP
\fB\-\-help\-gtk\fR
Show GTK+ Options
.SS "Application Options:"
.TP
\fB\-v\fR, \fB\-\-version\fR
Print version information and exit
.TP
\fB\-\-slideshow\fR
Start slideshow
.TP
\fB\-\-display\fR=\fI\,DISPLAY\/\fR
X display to use
.SH AUTHOR
gpicview was written by PCMan (Hong Jen Yee) <pcman.tw@gmail.com>.
.PP
This manual page was written by Ulises Vitulli <dererk@debian.org>
for the Debian project (but may be used by others).
